Operator: Skip building ix if the node does not exist in merkle tree (#261)
#### Problem

- Confirmed a panic in prod

```bash
2026-08-22 02:55:43.693 unk note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
2026-08-22 02:55:43.693 unk Node exists in meta merkle 
2026-08-22 02:55:43.693 unk thread 'tokio-rt-worker' (2608319) panicked at tip-router-operator-cli/src/tip_router.rs:237:18: 
```

#### Solution

- Skip building ix if the node does not exist in merkle tree like TDA


https://github.com/jito-foundation/jito-tip-router/blob/4caf4ddf4deaacd4648b05110a316abea0114a0c/tip-router-operator-cli/src/tip_router.rs#L130-L135