operator: Auto-catchup local RPC at turn of epoch (#133)
**Problem**
There is potential for our local snapshotting RPC to be behind the
remote validator at the turn of the epoch. This can cause problems when
attempting to load-bank-from-snapshot due to missing blocks on the
ledger.

**Solution**
- Add `localhost_port` argument which tells the catchup command how to
talk to our local RPC
- Wire through the `rpc_url` to the catchup config to ensure this is
cluster agnostic
- Invoke `solana catchup` programatically at operator startup to quickly
validate the `localhost_port`
- Invoke `solana catchup` programatically at the turn of the epoch

**Log Output**

testnet happy path
```
May 06 23:40:33 ny-testnet-rpc-2 tip-router-operator-cli[3005735]: [2025-05-06T23:40:33Z INFO  solana_metrics::metrics] host id: tip-router-operator-testnet-us-east-ny-testnet-rpc-2
May 06 23:40:33 ny-testnet-rpc-2 tip-router-operator-cli[3005735]: [2025-05-06T23:40:33Z INFO  tip_router_operator_cli] Catching up the localhost RPC with remote validator...
May 06 23:40:38 ny-testnet-rpc-2 tip-router-operator-cli[3005735]: [2025-05-06T23:40:38Z INFO  tip_router_operator_cli] 5PY5gjNgfaw89gz57GydmWafF9M2T5fnWGKgDR8H9rtS has caught up (us:332240775 them:332240775)
```

mainnet happy path
```
May 07 00:14:51 tip-router-rpc-2 tip-router-operator-cli[1237638]: [2025-05-07T00:14:51Z INFO  solana_metrics::metrics] host id: tip-router-operator-mainnet-eu-west-tip-router-rpc-2
May 07 00:14:51 tip-router-rpc-2 tip-router-operator-cli[1237638]: [2025-05-07T00:14:51Z INFO  tip_router_operator_cli] Ensuring localhost RPC is caught up with remote validator...
May 07 00:14:56 tip-router-rpc-2 tip-router-operator-cli[1237638]: [2025-05-07T00:14:56Z INFO  tip_router_operator_cli] waygveB1mod7sNk8P3njt7PjiVv2MpKjXraBiA8HByw has caught up (us:338318529 them:338318529)
```

failure case - incorrect port or localhost RPC not running
```
May 06 23:57:18 ny-testnet-rpc-2 systemd[1]: Started tip-router-operator.service - Tip Router Service.
May 06 23:57:18 ny-testnet-rpc-2 tip-router-operator-cli[3007759]: [2025-05-06T23:57:18Z INFO  solana_metrics::metrics] host id: tip-router-operator-testnet-us-east-ny-testnet-rpc-2
May 06 23:57:18 ny-testnet-rpc-2 tip-router-operator-cli[3007759]: [2025-05-06T23:57:18Z INFO  tip_router_operator_cli] Catching up the localhost RPC with remote validator...
May 06 23:57:18 ny-testnet-rpc-2 tip-router-operator-cli[3007759]: [2025-05-06T23:57:18Z INFO  solana_metrics::metrics] metrics configuration: host=http://tip-router.metrics.jito.wtf:8086 db=tip-router username=jito
May 06 23:57:18 ny-testnet-rpc-2 tip-router-operator-cli[3007759]: thread 'main' panicked at tip-router-operator-cli/src/main.rs:59:9:
May 06 23:57:18 ny-testnet-rpc-2 tip-router-operator-cli[3007759]: Failed to catch up: Failed to execute catchup command: error sending request for url (http://localhost:8899/): error trying to connect: tcp connect error: Connection refused (os error 111)
May 06 23:57:18 ny-testnet-rpc-2 tip-router-operator-cli[3007759]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 06 23:57:18 ny-testnet-rpc-2 tip-router-operator-cli[3007759]: [2025-05-06T23:57:18Z ERROR solana_metrics::metrics] datapoint: tip_router_cli.main,cluster=testnet operator_address="AkFvcJXjoKYYUNBJd66gGL6bCos6x5KUWZTZdmXQyks6" status="error" error="Failed to execute catchup command: error sending request for url (http://localhost:8899/): error trying to connect: tcp connect error: Connection refused (os error 111)" state="bootstrap"
May 06 23:57:18 ny-testnet-rpc-2 systemd[1]: tip-router-operator.service: Main process exited, code=exited, status=101/n/a
```